### ISSUE TITLE
Max and Min functions? Safer?

### ISSUE THREAD

**Issue by GriffGreen** [dapphub/ds-math#4]
Thank you guys for the beautiful readme! It really helped me understand the purpose of the code SOOOOO much more.

I am curious about the Max and Min functions. Do they actually prevent inaccurate answers in the case of overflow?

Specifically: 

`function min(uint256 x, uint256 y) constant internal returns (uint256 z) {`
`        return x <= y ? x : y;`

If i have `x== (2^256) +1` and `y == 100` would it actually give me the `y` (the expected answer by humans) or would it give me `x` the overflow making `x` look like a small number to 'puters.

I am a novice when it comes to computer science... I might be getting overflow wrong and using the wrong numbers, but I think you get my point.

Thank you again for the beautiful library and the hard work you have put into it, I am excited about implementing this into our Giveth projects 

Much love,
Griff

**Comment by ryepdx** [comment]
You should probably be using the other math functions in this module so you don't end up with an overflow in the first place.

**Comment by nmushegian** [comment]
> If i have `x== (2^256) +1`

This is a solidity expression, a word can't contain this "number", when x is evaluated then the value in the actual word data will be 1.

If x = 1 and y=100 then the minimum is x.

**Comment by GriffGreen** [comment]
Ok, so it does not protect for overflow. 

Then what is the advantage of the `max()` and `min()` over `>`, `>=`, `<` and `>=`

Thanks!

**Comment by dbrock** [comment]
@GriffGreen It's simply that in `max(x, y)`, you don't have to repeat the expressions `x` and `y`. If either of those are very long (rather than just one variable) then `x >= y ? x : y` obviously looks ridiculous. (And of course if either of them has a side-effect, then it might even produce the wrong results.)

And yeah, `min` and `max` don't even change `x` or `y` (it just returns one of them), so it really is a totally nonsensical idea to try to protect against overflow here. :smile: 

As @ryepdx said, you'll have to protect against overflow when you actually **change** the values (adding, subtracting, multiplying, etc.). 

Does that make sense?

**Comment by GriffGreen** [comment]
Yes, that makes perfect sense, :-D 

I worry about user (schiesty hacker) entered overflow that would circumvent checks using these functions... specifically we found a bug on our vault contract where a user could enter a delay time that would be read by solidity as a small number but might pass a check because it's actually a really large number :-D

https://github.com/Giveth/vaultcontract/commit/aa1d22f8e9d8b000400c287abbe4b79bacc50f22

I was hoping this would be a magical fix for it... but we can just add overflow protection the old fashioned way ;-D 

Thank you guys sooooo much for kicking up the documentation in this library over the last few days. It looks great! and makes so much more sense now :-D 

Much love,
Griff

**Comment by dbrock** [comment]
In the case you linked to, overflow could happen in the following code:

```
        p.earliestPayTime = _paymentDelay >= timeLock ?
                                now + _paymentDelay :
                                now + timeLock;
```

The solution would be to instead write this as follows:

```
        p.earliestPayTime = _paymentDelay >= timeLock ?
                                add(now, _paymentDelay) :
                                add(now, timeLock);
```

In general, any usage of the `+`, `-` and `*` operators can result in overflow (or underflow). Hence the recommendation to replace any instance of these with `add`, `sub` and `mul`.

So again, it's not a question of the `_paymentDelay` number _itself_ overflowing; that's a meaningless concept: a number simply is what it is. It's just that whenever you add two numbers using the `+` operator&mdash;under any circumstance&mdash;overflow may happen.

**Comment by GriffGreen** [comment]
oooo thank you! That is sooo interesting!

It would seem even more fun and concise to go with:

` p.earliestPayTime = max( add(now, _paymentDelay), add(now, timeLock) );`

:-D

Thank you so much for taking the time to explain this too me so politely... this is why I love working in the Ethereum Community :-) #LearningIsFun #MathIsCool

**Comment by dbrock** [comment]
Yep! Or even more concisely:
```
p.earliestPayTime = add(now, max(_paymentDelay, timeLock));
```
:clock430: :clock8: :haircut_man: :haircut_woman:
