### ISSUE TITLE
Allows dividing by 0?

### ISSUE THREAD

**Issue by izqui** [dapphub/ds-math#5]
Should dividing by 0 be allowed? IMO this is something that should be asserted against and if trying to divide by 0 cause a throw (i think it is unexpected that the divisor is 0). 

Also you are not asserting that the result of the division is correct.

**Comment by dbrock** [comment]
This is checked automatically by Solidity. https://github.com/ethereum/solidity/pull/888

As for the second question: when would the result be incorrect?

**Comment by izqui** [comment]
Didn't know about Solidity checking that, good to know.
